### ISSUE TITLE
All keys in doco and samples are encoded in ASCII

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.Encryption.MessageProperty#11]
This goes against our own recommendation:

> Use Base64 whenever possible.

### Plan of Attack

- [ ] Update doco
- [ ] Update upgrade guide
- [ ] Update samples

**Comment by SimonCropp** [comment]
@Particular/encryption-maintainers any progress on this ?

**Comment by MarcinHoppe** [comment]
@SimonCropp I'll update keys in the docs.

**Comment by SimonCropp** [comment]
@MarcinHoppe thanks
