### ISSUE TITLE
RijndaelEncryptionService.ConfigureIV use

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Encryption.MessageProperty#16]
Is there any reason RijndaelEncryptionService.ConfigureIV is virtual? nothing overrides it and there is no doco for it https://docs.particular.net/search?q=configureiv

        protected virtual void ConfigureIV(RijndaelManaged rijndael)
        {
            rijndael.GenerateIV();
        }

## Plan of attack

- [x] Mark class internal
- [x] Update/create upgrade guide

**Comment by ramonsmits** [comment]
@SimonCropp will look into this after the 21th.

**Comment by kbaley** [comment]
In [this PR](https://github.com/Particular/NServiceBus.Encryption.MessageProperty/pull/9/files) the class was made public I _think_ to rework how it was configured though I don't recall the details. @timbussmann might remember but regardless, that and likely all the other methods on it are undocumented.

**Comment by ramonsmits** [comment]
@SimonCropp Its these 3 apis that are required for testing purposes. https://github.com/Particular/NServiceBus.Encryption.MessageProperty/blob/e5cb56ccfbcc45f921d2f0afb235dd07ab174aac/src/MessageProperty/RijndaelEncryptionService.cs#L253-L275

They were made public because `RijndaelEncryptionService` is public and couldn't back then be made internal.

As we are now will be releasing a new major version I think we should consider making `RijndaelEncryptionService` private.

@Particular/encryption-maintainers Votes?

**Comment by MarcinHoppe** [comment]
👍 for making it private before RC.

**Comment by kbaley** [comment]
Even though it was a mistake, are we allowed to just make a public API private? Instead of marking it obsolete and deprecating it in v3?

**Comment by MarcinHoppe** [comment]
Of course, that's our way of prolonged "making it private" :).

**Comment by kbaley** [comment]
Another option: We could do a patch release 1.0.1 with the class marked `obsolete` before removing it in 2

**Comment by MarcinHoppe** [comment]
Touching public API seems to go against SemVer or am I misunderstanding your proposal?

**Comment by SimonCropp** [comment]
Semver allows breaking changes in a major

**Comment by SimonCropp** [comment]
Imo. If it was never intended to be used publically, and whatever people could have achieved by using it can be done in other ways, then just make it internal and add it to the upgrade guide. No need for an obsolete

**Comment by kbaley** [comment]
@Particular/encryption-maintainers I made a mistake about the scope. `RijaendelEncryptionService` is how we actually configure the feature: https://docs.particular.net/nservicebus/security/property-encryption. We can't make the entire class private. The `AddKeyIdentifierHeader`, `TryGetKeyIdentifierHeader`, and `ConfigureIV` methods appear to be virtual so they can be overridden to test the service itself. So we _could_ mark them internal and make them available to the acceptance tests.

**Comment by MarcinHoppe** [comment]
👍 for making those internal and exposing them via `[InternalsVisibleTo]`.

**Comment by kbaley** [comment]
PR for upgrade guide: https://github.com/Particular/docs.particular.net/pull/3231
