### ISSUE TITLE
Wire backward compatibility core v6/v7

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Encryption.MessageProperty#8]
When the encryption is obsoleted in the core with the next major version, we can no longer use `NServiceBus.WireEncryptedString` for the compatibility. This might become an issue when trying to process messages before the upgrade from core v6 to v7 (e.g. due to SC retries, timeouts, retries and so on).

Currently, we made no changes to `WireEncryptedString` in this repo from the version in the core, so it might be possible to "convert" the message type to the encryptions `WireEncryptedString` type in order to provide wire level backward compatibility.

**Comment by SimonCropp** [comment]
@Particular/encryption-maintainers i believe this is covered by this sln https://github.com/Particular/NServiceBus.WireCompatibilityTests/tree/master/Encryption  can u please re-open if that is not the case
